### ISSUE TITLE
many of images are not showing up correctly

### ISSUE THREAD

**Issue by JParkACR** [aws-samples/cfn101-workshop#105]
almost all of the images in the middle of sentence are not showing up.
I guess the link has broken or source image has gone.

For instance, 
AWS CFN 101 Workshop > Prerequisites > Create an AWS Account,
in the middle of sentence there is a blue string "new-user-1-png" without image.

**Comment by ConnorKirk** [comment]
Thanks Jay. We will investigate

**Comment by rezabekf** [comment]
Thank you for the issue @JParkACR. This is currently being investigated and is tracked here #102 . Please use this link in the meantime https://cfn101.sa.engineering until we fix official site.
