### ISSUE TITLE
pip not listed as prerequisite

### ISSUE THREAD

**Issue by cmenning** [aws-samples/cfn101-workshop#121]
pip is not listed as a prerequisite. Although it is addressed in the section for installing a linter (under the "install a code editor" section) it is not marked as a hard requirement. It's impossible to complete the lab without it, however, as you cannot bundle the lambda without it.

Since the linter is hidden away under "install a code editor" (which in turn is likely to be skipped over, since many people already have one) and additionally marked as "recommended" in any case, Python/pip should be promoted to a top-level prerequisite with install instructions for the major platforms.

**Comment by rezabekf** [comment]
Thanks Craig. Well spotted, I will add above to prerequisites. Thank you!

**Comment by rezabekf** [comment]
Hi Craig, I have reviewed the workshop and I trust `pip` is only required in the lab `Package and Deploy` where in step [2. Install function dependencies](https://cfn101.workshop.aws/intermediate/templates/package-and-deploy.html#2-install-function-dependencies) it mentions the use of `pip` and link to the official web-site.

The reason `pip` installation is not part of pre-req section is to reduce preparation time to go and start the workshop.

Hope this helps?
