### ISSUE TITLE
The `aws lambda invoke` command does not complete as written on Windows cmd or PowerShell

### ISSUE THREAD

**Issue by cmenning** [aws-samples/cfn101-workshop#122]
The following command does not complete as written on Windows (cmd or PowerShell):

`aws lambda invoke --function-name cfn-workshop-python-function --payload '{"time_zone": "Europe/London"}' --cli-binary-format raw-in-base64-out response.json`

In cmd, the output is:

```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: response.json
```

In PowerShell, the output is:

```
An error occurred (InvalidRequestContentException) when calling the Invoke operation: Could not parse request body into json: Could not parse payload into json: Unexpected character ('t' (code 116)): was expecting double-quote to start field name
 at [Source: (byte[])"{time_zone: Europe/London}"; line: 1, column: 3]
```

The PowerShell version is fixed by simply adding a backslash to escape each double-quote. I'm not sure off the top of my head about the cmd version.

**Comment by rezabekf** [comment]
Hi Craig, thanks for submitting the issue. The workshop was initially build with unix/linux systems, however I feel we should support WIN users too. At least at cli level. I will look into this and try to add separate tabs for WIN OS powershell and/or cmd.
