### ISSUE TITLE
Nested Stacks/ec2.yaml Security Group Needs access to https for yum installs

### ISSUE THREAD

**Issue by soyer-dev** [aws-samples/cfn101-workshop#127]
Security group used for the ec2 instance only allows outbound http calls, this causes yum to fail and stack can't be completed.

/code/workspace/nested-stacks/ec2.yaml

 SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

**Comment by rezabekf** [comment]
Fixed in #129
