### ISSUE TITLE
Feature request: adding preview for social media links

### ISSUE THREAD

**Issue by mrinaudo-aws** [aws-samples/cfn101-workshop#144]
Hello!  Would it be possible, for a given lab URL, to have a preview available (i.e., image + content description), so that it can be used in social media links (e.g., in a post from Twitter)?  Thank you!

**Comment by rezabekf** [comment]
Hi Matteo, thanks for the submission. I will put it in my backlog and look into this.

**Comment by rezabekf** [comment]
This is not possible since we moved away form the `hugo` framework and we do not have access to the new framework to do required changes.
