### ISSUE TITLE
Prequisites/AWS User - Do we need Admin Access?

### ISSUE THREAD

**Issue by ConnorKirk** [aws-samples/cfn101-workshop#15]
The current pre-requisite page gives instructions  to create a user with Admin access. 
Do we need it? I think Power User would be acceptable, given we're not creating IAM resources in the existing content.

Alternatively, I think we should add a justification explaining:
1. Why it is needed
2. A disclaimer about granting random things admin access

**Comment by rezabekf** [comment]
Hi Connor, the admin access is required due to a creating IAM role. Power user will not be sufficient policy for CFN to create IAM role.

For your second point, disclaimer can be found here https://cfn101.solution.builders/20-prerequisites/100-account/
