### ISSUE TITLE
Add a button to easily create issues to gather feedback

### ISSUE THREAD

**Issue by ConnorKirk** [aws-samples/cfn101-workshop#22]
Gathering feedback is a key way to improve this workshop. We should aim to make it as frictionless as possible for users to submit issues and improvements.

It is possible to [use query parameters with github to prefill an issue](https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters). Perhaps we could add a button to the hugo template that automagically creates an issue and prefills it with some basic information (eg Page/Lesson).

I'm not 100% sure if this is possible, but I will investigate

**Comment by rezabekf** [comment]
I have implemented simple Feedback/Issue to left hand menu. I trust this should be sufficient for now.
