### ISSUE TITLE
Correct flags used with cfn-signal 

### ISSUE THREAD

**Issue by bluecrayon52** [aws-samples/cfn101-workshop#74]
In Lab 09: Helper Scripts, step 4.2, the wrong flags are used with the cfn-signal script: 

`# Call cfn-signal script to send a signal with exit code 
      /opt/aws/bin/cfn-signal --exit-code $? -s ${AWS::StackName} -r WebServerInstance --region ${AWS::Region}`

[The Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-signal.html) states that the -s flag is short for --success, not --stack, and the -r flag is short for --reason, not --resource.  The correct flags are used in the solution template provided as follows:
 
`# Call cfn-signal script to send a signal with exit code
          /opt/aws/bin/cfn-signal --exit-code $? --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}`

[The lab](https://cfn101.solution.builders/30-workshop-part-01/30-launching-ec2/400-lab-09-helper-scripts/) code needs to be corrected.

**Comment by rezabekf** [comment]
Thanks @bluecrayon52 , the flags has been fixed.
