### ISSUE TITLE
Lab09 Missing - on resource options

### ISSUE THREAD

**Issue by sgalla1** [aws-samples/cfn101-workshop#76]
In the instructions for lab09, there is a missing "-" on the resource option in the EC2 user data.

Path: https://github.com/aws-samples/cfn101-workshop/blob/ed9b72b70568e020796f1d72c07d1388683ea4e3/workshop/content/30-workshop-part-01/30-launching-ec2/400-lab-09-helper-scripts.md#4-configure-cfn-signal-and-creationpolicy-attribute
Section 4.2

Current:
```
# Call cfn-signal script to send a signal with exit code 
/opt/aws/bin/cfn-signal --exit-code $? --stack ${AWS::StackName} -resource WebServerInstance --region ${AWS::Region}
```

Should be:
```
# Call cfn-signal script to send a signal with exit code 
/opt/aws/bin/cfn-signal --exit-code $? --stack ${AWS::StackName} --resource WebServerInstance --region ${AWS::Region}
```
It is ok in the corresponding yaml solution file

**Comment by rezabekf** [comment]
Thanks @sgalla1, for submitting the issue. It has been fixed now.
