### ISSUE TITLE
avoid error when aws lambda invoked

### ISSUE THREAD

**Issue by jinseo-jang** [aws-samples/cfn101-workshop#90]
In lab 12, when check if lambda works properly, Invalid base 64 error happened. So to avoid it, needed to add one more argument in aws cli.

```
aws lambda invoke \
--function-name cfn-workshop-python-function \
--payload '{"time_zone":"Europe/London"}' \
--cli-binary-format raw-in-base64-out \
response.json
```

Anyway, Thank you so much for good hands-on lab!

**Comment by rezabekf** [comment]
Thank you for the issue submission @jinseo-jang. I will look into this shortly.

**Comment by rezabekf** [comment]
Since awscli 2.0.0 was released, payloads need to be base64 encoded when invoking a lambda. For more details see aws/aws-cli#4968 Thank you for spotting this @jinseo-jang
