### ISSUE TITLE
Some code blocks are not being displayed properly

### ISSUE THREAD

**Issue by ctd** [aws-samples/cfn101-workshop#92]
On the workshop website there appears to be numerous bits of content that should be rendered as a code block, but are instead being rendered as a paragraph.

Example: Step 2 under `Fn::Ref` of https://cfn101.sa.engineering/30-workshop-part-01/20-cloudformation-features/200-lab-03-functions/

I fixed this in the first instance I came across in #91 but it seems to occur throughout the workshop.

Furthermore I've observed:
 - The blocks are shown correctly when using `hugo serve` on my own machine
 - The blocks are shown correctly through GitHub's Markdown rendering

I'm not sure what the cause is but I suspect so far that it's perhaps a difference in behaviour between the version of hugo I'm using, and what's building the published site.

**Comment by ConnorKirk** [comment]
Thanks Chris.
I've seen this issue before due to differences in the version of `hugo` in the amplify deployment, and the local tool. Perhaps it is the same case here. I will take a look.
