### ISSUE TITLE
Rules and Hooks section are missing in template anatomy

### ISSUE THREAD

**Issue by miparnisari** [aws-samples/cfn101-workshop#96]
See https://github.com/awsdocs/aws-cloudformation-user-guide/issues/794

Two sections are missing in https://cfn101.sa.engineering/30-workshop-part-01/10-cloudformation-fundamentals/100-template-anatomy/

- Rules
- Hooks

**Comment by ConnorKirk** [comment]
Thanks Maria! We will add this to the workshop

**Comment by toksvaeth** [comment]
@miparnisari Thanks for the improvement!

We'll update the workshop, but can you provide information as to when the central anatomy page will be updated?  We refer users to this and it would be neater to point them to a centralised resource rather than individual service documentation.
